# Generated by Django 4.0.3 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='localidad',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='servicio',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
