# Generated by Django 4.0.3 on 2022-11-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_alter_contacto_nombre_alter_contacto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='servicio',
            field=models.IntegerField(choices=[(1, 'Mensura'), (2, 'Estado parcelario'), (3, 'Relevamiento'), (4, 'Amojonamiento'), (5, 'Replanteo'), (6, 'Subdivision en Propiedad horizontal'), (7, 'Unificación'), (8, 'Loteo'), (9, 'Plano de usucapión'), (10, 'Barrio cerrado o club de campo')]),
        ),
    ]
