# Generated by Django 4.2.1 on 2023-08-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0004_alter_contacto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='servicio',
            field=models.IntegerField(choices=[(1, 'Mensura'), (2, 'Estado parcelario'), (3, 'Relevamiento'), (4, 'Amojonamiento'), (5, 'Replanteo'), (6, 'Subdivision en Propiedad horizontal'), (7, 'Unificación'), (8, 'Loteo'), (9, 'Plano de usucapión'), (10, 'Barrio cerrado o club de campo'), (11, 'Otro')]),
        ),
    ]
