# Generated by Django 4.2.1 on 2023-08-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_alter_contacto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='numero_telefono',
            field=models.CharField(max_length=10),
        ),
    ]
