# Generated by Django 4.0.3 on 2022-11-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=60)),
                ('telefono', models.CharField(max_length=30)),
                ('asunto', models.TextField(max_length=2000)),
            ],
        ),
    ]
